### ISSUE TITLE
config.json example

### ISSUE THREAD

**Issue by s3m1s0n1c** [Jrawke/DiscordMX#1]
Hey are you able to put an example config.json in the repo please

Thanks
Sonic

**Comment by Jrawke** [comment]
Hello, the project currently doesn't have a config.json. If you would like to add one feel free to open a PR. Thanks!

**Comment by Jrawke** [comment]
Actually we have one, it looks like this:

`
{
    "token": "YOUR_SECRET_TOKEN_HERE"
}
`

feel free to open a PR to add it to the repo
